trigger:
  branches:
    include:
      - main

variables:
  acrName: 'wahab2023'  # Replace with your Azure Container Registry name
  imageTag: '$(Build.BuildId)'  # Use the build ID as the image tag

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
steps:
  - task: Gradle@2
    displayName: 'Build with gradle'
    inputs:
      workingDirectory: ./build
      gradleWrapperFile: 'gradlew'
      task: 'clean build'

  - task: Docker@2
    inputs:
      containerRegistry: 'wahab2023.azurecr.io'  # Replace with your Azure Container Registry connection name
      repository: '$(acrName)'
      command: 'buildAndPush'
      Dockerfile: './dockerfile'  # Replace with the path to your Dockerfile
      tags: |
        $(imageTag)

          ## - script: echo "Running build..."
          #   displayName: 'Build Step 1'
          # - script: echo "Build completed successfully."
          #   displayName: 'Build Step 2'